name: GCC Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Release] 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
           
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Install Python Tools
      run: |
        python -m pip install pylint

    - name: Cache Conan packages
      run: |
        pip install -r requirements.txt

    - name: PyLint
      run: | 
        pylint --jobs=4 ./
