name: GCC Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Release] 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
           
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Install Python Tools
      run: |
        python -m pip install pylint
        pip install coverage
        pip install pytest

    - name: Cache Pip packages
      run: |
        pip install -r requirements.txt

    - name: Coverage
      run: |
        dir -l
        ls
        pytest ./
        coverage run --source=. -m pytest -s --junit-xml=$TEST_REPORT_XML
        coverage report
        coverage xml


    - name: PyLint
      run: | 
        pylint --jobs=4 ./
